MODULE parameter_module

    IMPLICIT NONE

    INTEGER, PARAMETER :: DP = 8

    INTEGER, PARAMETER :: MSG_FILE = 6

    REAL(KIND=DP), PARAMETER :: ZERO = 0._DP,  ONE = 1._DP,  TWO = 2._DP, THREE = 3._DP,   &
                            &  FOUR = 4._DP,  FIVE = 5._DP, SIX = 6._DP, SEVEN = 7._DP,   &
                            &  EIGHT = 8._DP, NINE = 9._DP, TWENTYSEVEN = 27._DP

    REAL(KIND=DP), PARAMETER :: HALF = ONE/TWO

    REAL(KIND=DP), PARAMETER :: ONE_THIRD = ONE/THREE, TWO_THIRD = TWO/THREE,    &
                            &  ONE_SIXTH = ONE/SIX


    INTEGER, PARAMETER :: NDIM = 2
    INTEGER, PARAMETER :: NDIM_Voigt = NDIM * (NDIM + 1) / 2
    INTEGER, PARAMETER :: NDIM_STRESS = 3 
    INTEGER, PARAMETER :: NDIM_STRESS_Voigt = NDIM_STRESS * (NDIM_STRESS + 1) / 2

    INTEGER, PARAMETER :: DIRLENGTH = 256
    INTEGER, PARAMETER :: MSGLENGTH = 256

    INTEGER, PARAMETER :: PLASTICITY_FLAG = 1

    REAL(DP), PARAMETER :: PI = 4._DP * ATAN(1._DP)

    REAL(DP), PARAMETER :: ERROR = 0.00000001_DP
    REAL(DP), PARAMETER :: TOLERANCE = 0.00000001_DP
    REAL(DP), PARAMETER :: NUM_SMALL = 0.00000000000000000001 ! 1E-20
    REAL(DP), PARAMETER :: ERROR_SMALL = 0.00001_DP

    REAL(DP), PARAMETER :: EXPLICIT_MARGIN = 0.95_DP

    CHARACTER(len=1), PARAMETER :: STRESS_TYPE = 'K'
    CONTAINS

        SUBROUTINE EXIT_FUNCTION
            WRITE(*, *) '!!******** EXIT FUNCTION REACHED ********!!'
            ! CALL XIT  !Abaqus Exit function
            CALL EXIT
        END SUBROUTINE EXIT_FUNCTION

END MODULE parameter_module
